export const AUTO_GENERATED_MARKER = '<!-- auto-generated by skedyul-changelog -->'
export const SKIP_TEMPLATE_MARKER = '<!-- skip-pr-template -->'
export const AUTO_TEMPLATED_LABEL = 'auto-templated'

export const CLASSIFICATION_LABELS = [
  'Bug Fix',
  'New Feature',
  'Infrastructure',
  'Data Fix or Migration',
] as const

export type ClassificationLabel = (typeof CLASSIFICATION_LABELS)[number]

export const REQUIRED_SECTIONS = [
  'The Problem',
  'Classification',
  'Solution',
  'Testing',
] as const

export const MIN_SECTION_LENGTH = 40

export interface TemplateValidationResult {
  compliant: boolean
  skipped: boolean
  reasons: string[]
  classification: ClassificationLabel | null
}

function normalizeHeading(line: string): string | null {
  const match = line.match(/^#{2,3}\s+(.+?)\s*$/)
  return match?.[1]?.trim().toLowerCase() ?? null
}

export function extractSectionContent(body: string, sectionTitle: string): string {
  const lines = body.split('\n')
  const target = sectionTitle.toLowerCase()
  let capturing = false
  const content: string[] = []

  for (const line of lines) {
    const heading = normalizeHeading(line)
    if (heading !== null) {
      if (heading === target) {
        capturing = true
        continue
      }
      if (capturing) break
    } else if (capturing) {
      content.push(line)
    }
  }

  return content.join('\n').trim()
}

export function parseClassification(body: string): ClassificationLabel | null {
  const section = extractSectionContent(body, 'Classification')
  if (!section) return null

  for (const label of CLASSIFICATION_LABELS) {
    const pattern = new RegExp(`^\\s*${escapeRegExp(label)}\\s*$`, 'im')
    if (pattern.test(section)) return label
  }

  return null
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export function validatePrTemplate(body: string | null | undefined): TemplateValidationResult {
  const text = (body ?? '').trim()
  const reasons: string[] = []

  if (!text) {
    return { compliant: false, skipped: false, reasons: ['PR body is empty'], classification: null }
  }

  if (text.includes(SKIP_TEMPLATE_MARKER)) {
    return { compliant: true, skipped: true, reasons: [], classification: parseClassification(text) }
  }

  const headings = text
    .split('\n')
    .map(normalizeHeading)
    .filter((heading): heading is string => heading !== null)

  for (const section of REQUIRED_SECTIONS) {
    if (!headings.includes(section.toLowerCase())) {
      reasons.push(`Missing required section: ${section}`)
    }
  }

  const classification = parseClassification(text)
  if (!classification) {
    reasons.push(`Classification must be exactly one of: ${CLASSIFICATION_LABELS.join(' | ')}`)
  }

  for (const section of REQUIRED_SECTIONS) {
    if (section === 'Classification') continue
    const content = extractSectionContent(text, section)
    if (content.length < MIN_SECTION_LENGTH) {
      reasons.push(`Section "${section}" is too short (minimum ${MIN_SECTION_LENGTH} characters)`)
    }
  }

  return { compliant: reasons.length === 0, skipped: false, reasons, classification }
}

export interface FallbackPrTemplateInput {
  existingBody?: string
  prTitle?: string
  branchName?: string
  baseSha: string
  headSha: string
  compareUrl?: string
  areas: string[]
  changedFiles: string[]
  commits: Array<{ shortSha: string; message: string }>
  classification: ClassificationLabel
  copilotUnavailable?: boolean
}

export function inferClassificationFromChanges(
  changedFiles: string[],
  commitMessages: string[],
): ClassificationLabel {
  const files = changedFiles.map((file) => file.toLowerCase())
  const messages = commitMessages.join('\n').toLowerCase()

  if (files.some((file) => file.startsWith('src/schemas/') || file.includes('crm'))) {
    return 'Data Fix or Migration'
  }

  if (
    files.some(
      (file) =>
        file.startsWith('.github/') ||
        file.startsWith('scripts/changelog/') ||
        file.startsWith('scripts/release/'),
    )
  ) {
    return 'Infrastructure'
  }

  if (/\b(fix|bug|hotfix|regression|broken)\b/.test(messages)) return 'Bug Fix'
  if (/\b(feat|feature|add|introduce|enable)\b/.test(messages)) return 'New Feature'
  if (files.some((file) => file.startsWith('docs/'))) return 'New Feature'

  return 'Infrastructure'
}

function padSection(text: string, minLength = MIN_SECTION_LENGTH): string {
  const trimmed = text.trim()
  if (trimmed.length >= minLength) return trimmed
  return `${trimmed}\n\n_Add detail in a follow-up edit if this automated summary is too brief._`
}

function extractExistingContext(existingBody?: string): string {
  const text = (existingBody ?? '').trim()
  if (!text || text.includes(AUTO_GENERATED_MARKER)) return ''
  const snippet = text.length > 600 ? `${text.slice(0, 600).trim()}…` : text
  return `\n\nPrior PR description:\n\n${snippet}`
}

export function renderTemplatedPrBody(input: FallbackPrTemplateInput): string {
  const areasText =
    input.areas.length > 0
      ? input.areas.map((area) => `\`${area}\``).join(', ')
      : '_general SDK changes_'

  const compareLine = input.compareUrl
    ? `Compare: ${input.compareUrl}`
    : `Compare: \`${input.baseSha.slice(0, 7)}..${input.headSha.slice(0, 7)}\``

  const commitLines =
    input.commits.length > 0
      ? input.commits.slice(0, 8).map((c) => `- \`${c.shortSha}\`: ${c.message}`).join('\n')
      : '- No commits detected in this range.'

  const fileLines =
    input.changedFiles.length > 0
      ? input.changedFiles.slice(0, 20).map((f) => `- \`${f}\``).join('\n')
      : '- No changed files detected.'

  const problem = padSection(
    `This SDK change affects ${areasText}. ${compareLine}.${extractExistingContext(input.existingBody)}`,
  )

  const solution = padSection(
    [`Updates span ${areasText}.`, '', 'Commits:', commitLines, '', 'Changed files:', fileLines].join(
      '\n',
    ),
  )

  const testing = padSection(
    input.copilotUnavailable
      ? `Reviewers should validate SDK behavior in affected areas (${areasText}). Generated from git metadata because Copilot CLI was unavailable.`
      : `Reviewers should validate SDK behavior in affected areas (${areasText}). Run \`pnpm test\` and \`pnpm build\`.`,
  )

  return [
    AUTO_GENERATED_MARKER,
    '',
    '## The Problem',
    '',
    problem,
    '',
    '## Classification',
    '',
    input.classification,
    '',
    '## Solution',
    '',
    solution,
    '',
    '## Testing',
    '',
    testing,
    '',
    '## Rollout notes',
    '',
    '_None_. Integration apps should pin the new exact npm version after stable publish.',
    '',
  ].join('\n')
}

export function suggestFallbackPrTitle(input: {
  prTitle?: string
  branchName?: string
  commits: Array<{ message: string }>
  areas: string[]
}): string {
  const existing = (input.prTitle ?? '').trim()
  if (existing && existing !== input.branchName && existing.length <= 120) return existing

  const firstCommit = input.commits[0]?.message?.split('\n')[0]?.trim()
  if (firstCommit && firstCommit.length <= 120) {
    return firstCommit.replace(/^(fix|feat|chore|docs|refactor|test)(\([^)]+\))?:?\s+/i, '')
  }

  return `Update ${input.areas[0] ?? 'SDK'}`
}
