// CRM Schema exports
export {
  // Zod schemas
  CRMFieldTypeSchema,
  CRMFieldRequirementSchema,
  CRMFieldOptionSchema,
  CRMFieldDefinitionSchema,
  CRMFieldSchemaZ,
  CRMModelSchemaZ,
  CRMCardinalitySchema,
  CRMOnDeleteSchema,
  CRMRelationshipLinkSchema,
  CRMRelationshipSchemaZ,
  CRMSchemaZ,
  // Types
  type CRMFieldType,
  type CRMFieldRequirement,
  type CRMFieldOption,
  type CRMFieldDefinition,
  type CRMFieldSchema,
  type CRMModelSchema,
  type CRMCardinality,
  type CRMOnDelete,
  type CRMRelationshipLink,
  type CRMRelationshipSchema,
  type CRMSchema,
  type CRMSchemaValidationResult,
  // Functions
  defineSchema,
  validateCRMSchema,
  parseCRMSchema,
  safeParseCRMSchema,
} from './crm-schema'

// Agent Schema v3 exports (skills-based, no stages)
export {
  // Constants
  AGENT_SCHEMA_VERSION_V3,
  // Schemas
  PersonaVoiceFormatV3Schema,
  PersonaVoiceV3Schema,
  PersonaV3Schema,
  ToolApprovalConfigSchema,
  ToolRefV3Schema,
  WorkingMemoryConfigSchema,
  ExternalMemoryConfigSchema,
  SemanticMemoryConfigSchema,
  MemoryConfigV3Schema,
  ResponsePolicySchema,
  PoliciesConfigV3Schema,
  RuntimeConfigV3Schema,
  AgentConfigV3Schema,
  AgentYAMLV3Schema,
  // Time Window Schemas
  TimeWindowTimeStampSchema,
  TimeWindowDayOfWeekSchema,
  TimeWindowSlotAgentSchema,
  ResponseModeSchema,
  TimeWindowBehaviorSchema,
  TimeWindowPolicySchema,
  TimeWindowPoliciesSchema,
  TimeWindowDefaultSchema,
  SchedulingDelaySchema,
  SchedulingPatternSchema,
  SchedulingBehaviorConfigSchema,
  // Types
  type PersonaVoiceFormatV3,
  type PersonaVoiceV3,
  type PersonaV3,
  type ToolApprovalConfig,
  type ToolRefV3,
  type WorkingMemoryConfig,
  type ExternalMemoryConfig,
  type SemanticMemoryConfig,
  type MemoryConfigV3,
  type ResponsePolicy,
  type PoliciesConfigV3,
  type RuntimeConfigV3,
  type AgentConfigV3,
  type AgentYAMLV3,
  // Time Window Types
  type TimeWindowTimeStamp,
  type TimeWindowDayOfWeek,
  type TimeWindowSlotAgent,
  type ResponseMode,
  type TimeWindowBehavior,
  type TimeWindowPolicy,
  type TimeWindowPolicies,
  type TimeWindowDefault,
  type SchedulingDelay,
  type SchedulingPattern,
  type SchedulingBehaviorConfig,
  // Functions
  defineAgentV3,
  validateAgentYAMLV3,
} from './agent-schema-v3'
